name: Docker Image CI
on:
  push:
    branches:
      - master
  schedule:
    - cron: 0 0 * * *
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        major: [ "0.6" ]
        os: [ alpine ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set variables
        id: vars
        working-directory: ${{ matrix.major }}/${{ matrix.os }}
        run: |
          echo ::set-output name=repository::${GITHUB_ACTOR}/$(basename ${GITHUB_REPOSITORY})
          echo ::set-output name=version::$(grep 'HFISH_VERSION ' Dockerfile | awk '{print $3}')
          echo ::set-output name=workdir::${{ matrix.major }}/${{ matrix.os }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ${{ steps.vars.outputs.workdir }}
          pull: true
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ steps.vars.outputs.repository }}:${{ matrix.major }}
            ${{ steps.vars.outputs.repository }}:${{ steps.vars.outputs.version }}
            ${{ steps.vars.outputs.repository }}:${{ steps.vars.outputs.version }}-${{ matrix.os }}
